# Generated by Django 5.2.16 on 2026-08-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0017_update_document_description_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfiguration",
            name="system_instructions_mode",
            field=models.CharField(
                choices=[
                    ("REPLACE", "Replace the context-derived prompt"),
                    ("EXTEND", "Append to the context-derived prompt"),
                ],
                default="REPLACE",
                help_text="REPLACE (default): system_instructions replaces the prompt the factory derives from context. EXTEND: it is appended to that prompt, so a corpus agent keeps its corpus persona and gains these instructions plus available_tools.",
                max_length=8,
            ),
        ),
    ]
