# Generated by Django 5.2.14 on 2026-06-04 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_researchreport_plan_memory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="researchreport",
            new_name="research_re_corpus__dd8510_idx",
            old_name="research_re_corpus__c00b86_idx",
        ),
        migrations.RenameIndex(
            model_name="researchreport",
            new_name="research_re_creator_df5195_idx",
            old_name="research_re_creator_a4eaa6_idx",
        ),
        migrations.RenameIndex(
            model_name="researchreport",
            new_name="research_re_status_1a140d_idx",
            old_name="research_re_status_b7a9f2_idx",
        ),
    ]
