# Generated by Django 5.2.16 on 2026-07-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0059_corpusgroup_corpusgroupgroupobjectpermission_and_more"),
        ("research", "0004_researchreport_workspace_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchreport",
            name="corpus_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Search across this group's visible corpora instead of the anchor corpus alone.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_reports",
                to="corpuses.corpusgroup",
            ),
        ),
    ]
