# Generated by Django 5.2.14 on 2026-06-20 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0023_source_permission_hot_path_indexes"),
        ("annotations", "0096_alter_authorityfrontier_discovery_state"),
        (
            "corpuses",
            "0057_rename_corpuses_co_corpus__vote_idx_corpuses_co_corpus__64f0b6_idx_and_more",
        ),
        ("documents", "0042_pendingcorpusimport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="corpusreference",
            index=models.Index(
                fields=["created_by_analysis", "is_provisional"],
                name="idx_corpusref_analysis_provis",
            ),
        ),
    ]
