# Generated by Django 3.2.9 on 2023-01-23 06:16

from django.db import migrations
import doclatticeserver.shared.defaults
import doclatticeserver.shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_alter_annotationlabel_label_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='tokens_jsons',
            field=doclatticeserver.shared.fields.NullableJSONField(blank=True, default=doclatticeserver.shared.defaults.jsonfield_empty_array, null=True),
        ),
    ]
