# Generated by Django 5.2.14 on 2026-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0087_seed_authority_key_equivalence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorityfrontier",
            name="discovery_state",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("discovered", "Source found, awaiting ingestion"),
                    ("ingested", "Document imported"),
                    ("resolved", "CorpusReference upgraded to RESOLVED"),
                    ("failed", "No source found"),
                    ("unsupported", "No provider can_handle"),
                    (
                        "blocked_license",
                        "Source found but license not on public-domain allowlist",
                    ),
                    (
                        "unlocated",
                        "Located text did not verify against the requested key",
                    ),
                    (
                        "pending_approval",
                        "Found, awaiting human approval before ingest",
                    ),
                ],
                db_index=True,
                default="queued",
                max_length=32,
            ),
        ),
    ]
