# Generated by Django 5.2.14 on 2026-06-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0095_merge_authority_namespace_leaves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorityfrontier",
            name="discovery_state",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("discovered", "Source found, awaiting ingestion"),
                    ("ingested", "Document imported"),
                    ("resolved", "CorpusReference upgraded to RESOLVED"),
                    ("failed", "No source found"),
                    ("unsupported", "No provider can_handle"),
                    ("blocked_license", "Provider license is not public-domain"),
                    (
                        "blocked_domain",
                        "Source domain not on the public-domain allowlist",
                    ),
                    (
                        "unlocated",
                        "Located text did not verify against the requested key",
                    ),
                    (
                        "pending_approval",
                        "Found, awaiting human approval before ingest",
                    ),
                    ("deferred_cap", "Deferred: per-jurisdiction cap reached"),
                ],
                db_index=True,
                default="queued",
                max_length=32,
            ),
        ),
    ]
