# Generated by Django 5.2.14 on 2026-06-21 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0098_authoritykeyequivalence_authority_key_equiv_no_self_reference",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="authoritynamespace",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_authority_namespaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authoritynamespace",
            name="source",
            field=models.CharField(
                choices=[
                    ("baseline", "Shipped baseline (loader-managed)"),
                    ("manual", "Hand-curated (runtime override)"),
                ],
                db_index=True,
                default="baseline",
                max_length=16,
            ),
        ),
    ]
