# Generated by Django 5.2.8 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0101_authoritynamespace_baseline_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorityRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(db_index=True, max_length=255)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("CITES", "CITES"),
                            ("AMENDS", "AMENDS"),
                            ("SUPERSEDES", "SUPERSEDES"),
                            ("SUPERSEDED_BY", "SUPERSEDED_BY"),
                            ("ADOPTS", "ADOPTS"),
                            ("PARTIALLY_ADOPTS", "PARTIALLY_ADOPTS"),
                            ("REJECTS", "REJECTS"),
                            ("IMPLEMENTS", "IMPLEMENTS"),
                            ("INTERPRETS", "INTERPRETS"),
                            ("FILED_IN", "FILED_IN"),
                            ("RESPONDS_TO", "RESPONDS_TO"),
                            ("REVISES", "REVISES"),
                            ("INCORPORATES", "INCORPORATES"),
                            ("REQUIRES_FORM", "REQUIRES_FORM"),
                            ("EXCEPTION_TO", "EXCEPTION_TO"),
                            ("EFFECTIVE_VERSION_OF", "EFFECTIVE_VERSION_OF"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("target_key", models.CharField(db_index=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("baseline", "Authority pack baseline"),
                            ("provider", "Source provider"),
                            ("manual", "Hand-curated"),
                        ],
                        db_index=True,
                        default="baseline",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("verified", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_key", "relationship_type"],
                        name="auth_rel_source_type_idx",
                    ),
                    models.Index(
                        fields=["target_key", "relationship_type"],
                        name="auth_rel_target_type_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_key", "relationship_type", "target_key"),
                        name="authority_relationship_unique_edge",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(source_key=models.F("target_key")),
                        name="authority_relationship_no_self_edge",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            relationship_type__in=(
                                "CITES",
                                "AMENDS",
                                "SUPERSEDES",
                                "SUPERSEDED_BY",
                                "ADOPTS",
                                "PARTIALLY_ADOPTS",
                                "REJECTS",
                                "IMPLEMENTS",
                                "INTERPRETS",
                                "FILED_IN",
                                "RESPONDS_TO",
                                "REVISES",
                                "INCORPORATES",
                                "REQUIRES_FORM",
                                "EXCEPTION_TO",
                                "EFFECTIVE_VERSION_OF",
                            )
                        ),
                        name="authority_relationship_valid_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            source__in=("baseline", "provider", "manual")
                        ),
                        name="authority_relationship_valid_source",
                    ),
                ],
            },
        ),
    ]
