# Generated by Django 5.2.16 on 2026-08-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0102_authorityrelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorityfrontier",
            name="authority_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("statute", "statute"),
                    ("regulation", "regulation"),
                    ("admin-rule", "admin-rule"),
                    ("municipal-ordinance", "municipal-ordinance"),
                    ("case", "case"),
                    ("constitution", "constitution"),
                    ("court-rule", "court-rule"),
                    ("guidance", "guidance"),
                    ("treaty", "treaty"),
                    ("bill", "bill"),
                ],
                db_index=True,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="authoritynamespace",
            name="authority_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("statute", "statute"),
                    ("regulation", "regulation"),
                    ("admin-rule", "admin-rule"),
                    ("municipal-ordinance", "municipal-ordinance"),
                    ("case", "case"),
                    ("constitution", "constitution"),
                    ("court-rule", "court-rule"),
                    ("guidance", "guidance"),
                    ("treaty", "treaty"),
                    ("bill", "bill"),
                ],
                db_index=True,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="corpusreference",
            name="authority_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("statute", "statute"),
                    ("regulation", "regulation"),
                    ("admin-rule", "admin-rule"),
                    ("municipal-ordinance", "municipal-ordinance"),
                    ("case", "case"),
                    ("constitution", "constitution"),
                    ("court-rule", "court-rule"),
                    ("guidance", "guidance"),
                    ("treaty", "treaty"),
                    ("bill", "bill"),
                ],
                db_index=True,
                max_length=32,
                null=True,
            ),
        ),
    ]
