# Generated by Django 5.2.14 on 2026-05-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0021_hash_analysis_callback_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "CREATED"),
                    ("QUEUED", "QUEUED"),
                    ("RUNNING", "RUNNING"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="CREATED",
                max_length=24,
            ),
        ),
    ]
