# Generated by Django 5.2.14 on 2026-05-28 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0052_corpus_preferred_llm"),
        ("documents", "0039_add_preferred_enrichers_to_pipeline_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="readme_caml_document",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Auto-maintained pointer to the corpus's Readme.CAML Document (the canonical source for the description). Refreshed via post_save signal on Document. Do not write directly. ``related_name='+'`` because Document↔Corpus is mediated by DocumentPath; there is no useful reverse accessor here.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.document",
            ),
        ),
    ]
