# Generated by Django 5.2.14 on 2026-06-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0056_corpus_auto_branding_enabled"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="corpusvote",
            new_name="corpuses_co_corpus__64f0b6_idx",
            old_name="corpuses_co_corpus__vote_idx",
        ),
        migrations.RenameIndex(
            model_name="corpusvote",
            new_name="corpuses_co_creator_912c61_idx",
            old_name="corpuses_co_creator_idx",
        ),
        migrations.RenameIndex(
            model_name="corpusvote",
            new_name="corpuses_co_session_4e4eaf_idx",
            old_name="corpuses_co_session_idx",
        ),
        migrations.AlterField(
            model_name="corpusvote",
            name="backend_lock",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
