# Generated by Django 5.2.16 on 2026-08-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0018_agentconfiguration_system_instructions_mode"),
        ("corpuses", "0059_corpusgroup_corpusgroupgroupobjectpermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="default_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent used for corpus chat when the caller names none. Must be GLOBAL or scoped to this same corpus. Prefer system_instructions_mode=EXTEND, which appends to this corpus's corpus_agent_instructions rather than replacing them.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_corpuses",
                to="agents.agentconfiguration",
            ),
        ),
    ]
