# Generated by Django 5.2.16 on 2026-08-26 13:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0060_corpus_default_agent"),
        ("worker_uploads", "0004_rename_placeholder_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerAuthoritySectionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Section-spec payload: {'sections': [...], 'equivalences': [...]}."
                    ),
                ),
                (
                    "report",
                    models.JSONField(
                        default=dict,
                        help_text="Bootstrap + equivalence outcome counts after processing.",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("processing_started", models.DateTimeField(blank=True, null=True)),
                ("processing_finished", models.DateTimeField(blank=True, null=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        help_text="Authority corpus this batch bootstraps into.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_section_batches",
                        to="corpuses.corpus",
                    ),
                ),
                (
                    "corpus_access_token",
                    models.ForeignKey(
                        help_text="Token used for this batch.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="section_batches",
                        to="worker_uploads.corpusaccesstoken",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
                "indexes": [
                    models.Index(
                        fields=["status", "created"],
                        name="worker_uplo_status_6fb47b_idx",
                    ),
                    models.Index(
                        fields=["corpus", "status"],
                        name="worker_uplo_corpus__c7271c_idx",
                    ),
                ],
            },
        ),
    ]
