# Generated by Django 5.2.16 on 2026-08-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker_uploads", "0005_workerauthoritysectionbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusaccesstoken",
            name="can_push_authority_sections",
            field=models.BooleanField(
                default=False,
                help_text="Whether this token may push authority-section batches (bootstrap_authority_corpus) in addition to plain document uploads.",
            ),
        ),
    ]
