# Generated by Django 5.2.16 on 2026-07-27 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0043_add_file_converter_support"),
        ("research", "0003_rename_researchreport_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchreport",
            name="workspace_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Markdown copy of this report filed in the creator's personal 'My Documents' workspace. A convenience link, not the idempotency key — the save is keyed by path, so re-finalizing versions the same file in place. Null when the report has not completed, or when the (deliberately non-fatal) workspace write failed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_report_saves",
                to="documents.document",
            ),
        ),
    ]
