# Generated by Django 5.2.15 on 2026-07-07 01:43

import django.db.models.deletion
import opencontractserver.shared.user_can_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0017_update_document_description_prompt"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("corpuses", "0058_artifact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpusGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backend_lock", models.BooleanField(db_index=True, default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier agents use to reference this group (e.g., 'bolivian-laws')",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "corpora",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The corpora this group bundles for cross-corpus retrieval",
                        related_name="corpus_groups",
                        to="corpuses.corpus",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Orchestrator agent bound to this group. Its system_instructions hold the orchestrator persona and its available_tools should include 'search_across_corpora'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_corpus_groups",
                        to="agents.agentconfiguration",
                    ),
                ),
                (
                    "user_lock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "permissions": (
                    ("permission_corpusgroup", "permission corpusgroup"),
                    ("publish_corpusgroup", "publish corpusgroup"),
                    ("create_corpusgroup", "create corpusgroup"),
                    ("read_corpusgroup", "read corpusgroup"),
                    ("update_corpusgroup", "update corpusgroup"),
                    ("remove_corpusgroup", "delete corpusgroup"),
                    ("comment_corpusgroup", "comment corpusgroup"),
                ),
            },
            bases=(
                opencontractserver.shared.user_can_mixin.InstanceUserCanMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CorpusGroupGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpuses.corpusgroup",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="CorpusGroupUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpuses.corpusgroup",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
    ]
