# Generated by Django 5.2.14 on 2026-06-16 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0023_source_permission_hot_path_indexes"),
        ("notifications", "0005_add_research_report_notification_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                help_text="Related analysis job, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="analyzer.analysis",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REPLY", "Reply to Message"),
                    ("VOTE", "Vote on Message"),
                    ("BADGE", "Badge Awarded"),
                    ("MENTION", "Mentioned in Message"),
                    ("ACCEPTED", "Answer Accepted"),
                    ("THREAD_LOCKED", "Thread Locked"),
                    ("THREAD_UNLOCKED", "Thread Unlocked"),
                    ("THREAD_PINNED", "Thread Pinned"),
                    ("THREAD_UNPINNED", "Thread Unpinned"),
                    ("MESSAGE_DELETED", "Message Deleted"),
                    ("THREAD_DELETED", "Thread Deleted"),
                    ("MESSAGE_RESTORED", "Message Restored"),
                    ("THREAD_RESTORED", "Thread Restored"),
                    ("THREAD_REPLY", "Reply in Thread You're Participating In"),
                    ("DOCUMENT_PROCESSED", "Document Processing Complete"),
                    ("DOCUMENT_PROCESSING_FAILED", "Document Processing Failed"),
                    ("EXTRACT_COMPLETE", "Extract Complete"),
                    ("ANALYSIS_RUNNING", "Analysis Running"),
                    ("ANALYSIS_COMPLETE", "Analysis Complete"),
                    ("ANALYSIS_FAILED", "Analysis Failed"),
                    ("EXPORT_COMPLETE", "Export Complete"),
                    ("DOCUMENT_PUBLICIZED", "Document Made Public via Corpus"),
                    ("RESEARCH_REPORT_COMPLETE", "Research Report Complete"),
                    ("RESEARCH_REPORT_FAILED", "Research Report Failed"),
                    ("RESEARCH_REPORT_CANCELLED", "Research Report Cancelled"),
                    ("RESEARCH_REPORT_PROGRESS", "Research Report Progress"),
                ],
                help_text="Type of notification",
                max_length=30,
            ),
        ),
    ]
