# Generated by Django 3.2.9 on 2023-03-02 04:48

from django.db import migrations, models
import doclatticeserver.types.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_initial_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexport',
            name='format',
            field=models.CharField(choices=[('LangChain Format', 'LANGCHAIN'), ('DocLattice Format', 'DOCLATTICE')], default=doclatticeserver.types.enums.ExportType['DOCLATTICE'], max_length=128),
        ),
    ]
