# Generated by Django 3.2.9 on 2023-03-08 04:22

from django.db import migrations, models
import doclatticeserver.types.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_zip_userexport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexport',
            name='format',
            field=models.CharField(choices=[('LANGCHAIN', 'LANGCHAIN'), ('DOCLATTICE', 'DOCLATTICE'), ('FUNSD', 'FUNSD')], default=doclatticeserver.types.enums.ExportType['DOCLATTICE'], max_length=128),
        ),
    ]
